import { StyleSheet } from 'react-native';
import { Theme } from './theme';

/** Karty i odstępy — duże, proste, czytelne (senior / słabszy wzrok). */
export const SeniorFlow = StyleSheet.create({
  headerStrip: {
    paddingHorizontal: Theme.spacing.l,
    paddingBottom: Theme.spacing.m,
    borderBottomWidth: 1,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerGreeting: {
    flex: 1,
    paddingRight: Theme.spacing.m,
  },
  headerGreetingLine: {
    fontSize: Theme.typography.body,
    fontWeight: '600',
  },
  headerName: {
    marginTop: 4,
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.s,
  },
  iconBtn: {
    minWidth: 52,
    minHeight: 52,
    borderRadius: Theme.borderRadius.medium,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
  },
  scroll: {
    paddingHorizontal: Theme.spacing.l,
    paddingTop: Theme.spacing.m,
    paddingBottom: Theme.spacing.xxl,
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: Theme.spacing.s,
    marginTop: Theme.spacing.l,
  },
  heroCard: {
    borderRadius: Theme.borderRadius.xlarge,
    padding: Theme.spacing.l,
    marginBottom: Theme.spacing.m,
    borderWidth: 1.5,
    alignItems: 'center',
    shadowColor: Theme.colors.shadowNeutral,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 4,
  },
  clock: {
    fontSize: 64,
    fontWeight: '900',
    letterSpacing: -2,
    lineHeight: 70,
  },
  heroDivider: {
    width: '100%',
    height: 1,
    marginVertical: Theme.spacing.m,
  },
  surfaceCard: {
    borderRadius: Theme.borderRadius.xlarge,
    padding: Theme.spacing.l,
    marginBottom: Theme.spacing.m,
    borderWidth: 1.5,
    shadowColor: Theme.colors.shadowNeutral,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  rowCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: Theme.borderRadius.large,
    padding: Theme.spacing.m,
    marginBottom: Theme.spacing.s,
    borderWidth: 1.5,
    gap: Theme.spacing.m,
    overflow: 'hidden',
  },
  rowAccent: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 5,
  },
  timeBadge: {
    minWidth: 76,
    paddingVertical: Theme.spacing.s,
    paddingHorizontal: Theme.spacing.s,
    borderRadius: Theme.borderRadius.medium,
    alignItems: 'center',
    borderWidth: 1,
  },
  activityTime: {
    fontSize: 20,
    fontWeight: '800',
  },
  activityName: {
    flex: 1,
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 26,
  },
  linkCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: Theme.borderRadius.large,
    padding: Theme.spacing.m,
    marginBottom: Theme.spacing.m,
    borderWidth: 1.5,
    gap: Theme.spacing.m,
  },
  linkIconCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    justifyContent: 'center',
    alignItems: 'center',
  },
  linkTitle: {
    flex: 1,
    fontSize: 20,
    fontWeight: '800',
  },
});
